version: 2

sources:
    - name: staging
      database: us-domestic-flights-356906
      schema: us_domestic_flights

      # loaded_at_field: record_loaded_at
      tables:
        - name: flights

models:
    - name: flight_data
      description: >
        Monthly US domestic flights records from 1990 to 2009. 
        The records were collected and provided by the US Census Bureau and RITA/Transtats, 
        Bureau of Transportation Statistics.
      columns:
          - name: origin_city
            description: Primary key for this table
            tests:
                - not_null:
                    severity: warn
          - name: origin_code
            description: Three letter airport code of the origin airport.
          - name: destination_code 
            description: Three letter airport code of the destination airport.
          - name: origin_city 
            description: Origin city name.
            tests:
              - relationships:
                  to: ref('us_cities_codes')
                  field: city
                  severity: warn
          - name: origin_state 
            description: Origin state name.
          - name: destination_city
            description: Destination city name.
            tests:
              - relationships:
                  to: ref('us_cities_codes')
                  field: city
                  severity: warn
          - name: destination_state 
            description: > 
              Destination state name.
          - name: flight_date 
            description: The date (yyyymm) of flight.
          - name: passengers 
            description: Number of passengers transported from origin to destination.
          - name: seats 
            description: >
              Number of seats available on flights from origin to destination.
          - name: no_of_flights
            description: Number of flights between origin and destination (multiple records for one month, many with flights > 1).
            tests:
                - not_null:
                    severity: warn
          - name: distance 
            description: > 
              Distance (to nearest mile) flown between origin and destination.
          - name: origin_population 
            description: > 
              Origin city's population as reported by US Census.
          - name: destination_population 
            description: > 
              Destination city's population as reported by US Census.
          